version: '3.8'

services:
  tts-service:
    build: .
    container_name: local-tts-service
    # 更新端口映射：
    # 主机端口由 .env 文件中的 TTS_PORT 定义，如果 .env 文件或该变量不存在，则默认为 5050。
    # 容器端口也应与 config.json 中定义的端口一致 (这里假设也是 5050)。
    ports:
      - "${TTS_PORT:-5050}:5050"
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped