version: "3.8"

services:
  tts-service:
    build:
      context: .
      args:
        # 将宿主机的环境变量传递给 Docker 构建过程
        - PIP_INDEX_URL
    container_name: local-tts-service
    ports:
      - "${TTS_PORT:-5050}:5050"
    volumes:
      - ./config.json:/app/config.json
      - ./tts_data:/app/tts_data
    restart: unless-stopped
